version: "2"

services: 
  ceramic-apache2:
    build: .
    container_name: ceramic-apache2
    ports:
      - '8000:8000'
      - '3500:3500'
      - '8006:81'
    volumes: 
      - $PWD/www:/var/www/html
