# Generated by Django 3.1.6 on 2021-08-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CeramicApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='header_en',
            field=models.TextField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='note',
            name='header_ru',
            field=models.TextField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='note',
            name='text_en',
            field=models.TextField(max_length=2000, null=True, verbose_name='Текст заметки'),
        ),
        migrations.AddField(
            model_name='note',
            name='text_ru',
            field=models.TextField(max_length=2000, null=True, verbose_name='Текст заметки'),
        ),
    ]
