# Generated by Django 3.1.6 on 2021-08-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CeramicApp', '0002_auto_20210826_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='short_name',
            field=models.TextField(choices=[('en', 'En'), ('ru', 'Ru')], max_length=2, verbose_name='Короткое название'),
        ),
    ]
