# Generated by Django 3.2.7 on 2021-09-01 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CeramicApp', '0004_auto_20210901_1647'),
        ('CeramicApp', '0005_load_intial_data'),
    ]

    operations = [
    ]
